---
title: "PCA Example (Iris)"
author: "Hayden Ginman"
date: "2023-04-24"
output: html_document
---
Install the requisite packages to easily perform PCA and load the required libraries
```{r}
options(repos = c(CRAN = "https://cran.rstudio.com"))
# install.packages(c("tidyverse", "FactoMineR", "factoextra", "ggcorrplot"))
library(tidyverse)
library(FactoMineR)
library(factoextra)
library(ggcorrplot)

```
Load the Iris dataset
```{r}
data("iris")

```
Briefly explore dataset
```{r}
head(iris)
summary(iris)

```

Normalize the dataset
```{r}
iris_norm <- iris %>% select(-Species)
iris_scale <- scale(iris_norm)

```
Compute and visualize the covariance matrix
```{r}
cov_matrix_scaled <- cov(iris_scale)
heatmap_plot <- ggcorrplot(cov_matrix_scaled, hc.order = TRUE, type = "lower",
                           lab = TRUE, lab_size = 3, tl.cex = 12, title = "Heatmap of Covariance Matrix")
print(heatmap_plot)
```




Calculate and display principal components
```{r}
p_comp <- prcomp(iris_scale)
print(p_comp)

```

Perform PCA on the dataset
```{r}
pca <- PCA(iris_scale, scale.unit = TRUE, graph = FALSE)

```
Print a summary of the PCA results
```{r}
summary(pca)
```
Visualize the PCA results
```{r}
fviz_eig(pca, addlabels = TRUE, ylim = c(0, 100), ggtheme = theme_minimal())

fviz_pca_biplot(pca, label = "var", habillage = iris$Species,
                addEllipses = TRUE, ellipse.type = "confidence",
                palette = "jco", ggtheme = theme_minimal())

```
Transform the data
```{r}
loadings <- pca$var$coord[, 1:2]
transformed_data <- as.data.frame(iris_scale %*% loadings)
transformed_data$Species <- iris$Species
colnames(transformed_data) <- c("PC1", "PC2", "Species")

ggplot(transformed_data, aes(x = PC1, y = PC2, color = Species)) +
  geom_point(size = 3) +
  theme_minimal() +
  labs(title = "PCA of Iris Dataset",
       x = "Principal Component 1",
       y = "Principal Component 2",
       color = "Species")
```